import type { Pillar } from "./types/pillars";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://gottwald.world";
const SITE_NAME = "GOTT WALD Holding LLC";
// Meta description — trimmed to ~155 chars so Google renders the full snippet
// on desktop and mobile SERPs (longer strings get truncated with an ellipsis).
const DEFAULT_DESCRIPTION =
  "Standards-led holding company in Tbilisi, Georgia. Operating-grade systems for people and strategic assets — clarity, execution, measurable impact.";
// Must exist in `public/` for reliable social previews.
// Choose a wide banner image already present in the repo.
const DEFAULT_OG_IMAGE = `${SITE_URL}/images/about_horizontal_2.png`;
const CONTACT_EMAIL = "office@gottwald.world";
const CONTACT_PHONE = "+995 591 086 578";
// Populate as public profiles go live — drives AI knowledge-panel matching.
// Each entry is a URL that represents THIS entity on another platform.
// YouTube is hardcoded (owned + stable). Everything else is read from env vars
// so URLs can be added on Vercel dashboard without code deploys. Empty values
// are filtered out so the `sameAs` schema stays clean.
const SOCIAL_PROFILES: string[] = [
  "https://www.youtube.com/channel/UCvcWaJx2dcqiLAfrPkspYiw",
  process.env.NEXT_PUBLIC_SOCIAL_LINKEDIN,
  process.env.NEXT_PUBLIC_SOCIAL_CRUNCHBASE,
  process.env.NEXT_PUBLIC_SOCIAL_X,
  process.env.NEXT_PUBLIC_SOCIAL_WIKIDATA,
  process.env.NEXT_PUBLIC_SOCIAL_FACEBOOK,
  process.env.NEXT_PUBLIC_SOCIAL_INSTAGRAM,
  process.env.NEXT_PUBLIC_SOCIAL_GITHUB,
].filter((url): url is string => Boolean(url?.trim()));

export {
  SITE_URL,
  SITE_NAME,
  DEFAULT_DESCRIPTION,
  DEFAULT_OG_IMAGE,
  CONTACT_EMAIL,
  CONTACT_PHONE,
};

// ---------------------------------------------------------------------------
// Organization — deep entity graph for AI knowledge extraction
// ---------------------------------------------------------------------------
export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    // Dual-type adds "Corporation" semantics without pulling in LocalBusiness
    // requirements (openingHoursSpecification, etc.) that ProfessionalService
    // would have triggered.
    "@type": ["Organization", "Corporation"],
    "@id": `${SITE_URL}/#organization`,
    name: SITE_NAME,
    legalName: "GOTT WALD Holding LLC",
    // Slogan is a citable, AI-quotable claim. Mirrors the site-wide hero copy
    // verbatim so retrieval-grounded answers can quote it accurately.
    slogan: "Turning complexity into clarity, decisions into measurable impact",
    url: SITE_URL,
    logo: {
      "@type": "ImageObject",
      url: `${SITE_URL}/logo-horizontal.png`,
      width: 600,
      height: 327,
      thumbnail: {
        "@type": "ImageObject",
        url: `${SITE_URL}/logo.png`,
        width: 160,
        height: 160,
      },
    },
    // Branded OG card (generated by app/opengraph-image.tsx) rather than an
    // ambient photo — stronger signal for Google's Knowledge Panel.
    image: `${SITE_URL}/opengraph-image`,
    description: DEFAULT_DESCRIPTION,
    foundingDate: "2024",
    foundingLocation: {
      "@type": "Place",
      name: "Tbilisi, Georgia",
    },
    address: {
      "@type": "PostalAddress",
      streetAddress: "Maseli Street N2a, Entrance N2, Office N201, Block G",
      addressLocality: "Tbilisi",
      addressRegion: "Gldani District",
      postalCode: "0167",
      addressCountry: "GE",
    },
    email: CONTACT_EMAIL,
    telephone: CONTACT_PHONE,
    contactPoint: [
      {
        "@type": "ContactPoint",
        contactType: "customer support",
        email: CONTACT_EMAIL,
        telephone: CONTACT_PHONE,
        areaServed: ["GE", "EU"],
        availableLanguage: ["English", "German"],
      },
      {
        "@type": "ContactPoint",
        contactType: "partnerships",
        email: CONTACT_EMAIL,
        url: `${SITE_URL}/partnerships`,
        availableLanguage: ["English", "German"],
      },
      {
        "@type": "ContactPoint",
        contactType: "media relations",
        email: CONTACT_EMAIL,
        url: `${SITE_URL}/press-media-kit`,
        availableLanguage: ["English", "German"],
      },
    ],
    identifier: [
      {
        "@type": "PropertyValue",
        propertyID: "Georgia Company Registration ID",
        value: "400415421",
      },
    ],
    areaServed: [
      { "@type": "Country", name: "Georgia" },
      // Broad coverage: Europe (keeps claims accurate without listing every country)
      { "@type": "Continent", name: "Europe" },
      { "@type": "GeoCircle", geoMidpoint: { "@type": "GeoCoordinates", latitude: 41.7151, longitude: 44.8271 }, geoRadius: "5000 km" },
    ],
    knowsAbout: [
      "Strategic Consulting",
      "IT Solutions for SMEs",
      "Business Relocation to Georgia",
      "Executive Coaching & Mentoring",
      "Marketing & Communication Infrastructure",
      "Digital Transformation",
      "Standards-Led Governance",
      "Holding Company Operations",
      "AI-Readable Web Architecture",
      "Frequency & Wellness Technology",
    ],
    // Audience signal lets AI engines match GOTT WALD against intent queries
    // ("a holding company for SME owners", "executive coaching for principals").
    audience: {
      "@type": "BusinessAudience",
      audienceType:
        "SME owners, executive leadership, principals, strategic investors, values-aligned operators",
      geographicArea: { "@type": "Continent", name: "Europe" },
    },
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "GOTT WALD Structural Pillars",
      itemListElement: [
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "IT Solutions 2030", description: "Homepage transformation & future-ready digital infrastructure for SMEs", url: `${SITE_URL}/our-work/it-solutions-2030` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "SolutionFinder & Management", description: "Structured analysis and systemic resolution of complex business situations", url: `${SITE_URL}/our-work/solutionfinder-solution-management` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Consulting", description: "Strategy architecture, organizational design, and scalable systems", url: `${SITE_URL}/our-work/consulting` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Coaching & Mentoring", description: "Executive coaching, identity & decision strength, holistic performance", url: `${SITE_URL}/our-work/coaching-mentoring` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Marketing & Communication", description: "Executive visibility, engineered trust, predictable demand infrastructure", url: `${SITE_URL}/our-work/marketing-communication` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Relocation & Strategic Deployment", description: "Corporate/holding setup, executive residency, and operational continuity in Georgia", url: `${SITE_URL}/our-work/relocation-structure-deployment` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "YIG.CARE", description: "Frequency and wellness care for sustained leadership performance — Inner Glow as strategic infrastructure", url: `${SITE_URL}/our-work/yigcare` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "PLHH Coin", description: "Real-world-asset governance layer — Peace, Love & Harmony for more Humanity", url: `${SITE_URL}/our-work/plhhcoin` } },
      ],
    },
    // Patron reference — minimal Person object per the audit Section 5
    // instruction: name only, no @id, no url, no sameAs, no biography, no
    // jobTitle, no credentials. The Holding stays the subject; the Patron
    // is one small, correctly-named property of the Organization.
    patron: {
      "@type": "Person",
      name: "Mathias Gottwald",
    },
    sameAs: SOCIAL_PROFILES,
  };
}

// ---------------------------------------------------------------------------
// WebSite — identifies the site-wide entity and its publisher.
// No SearchAction: the site has no on-site search endpoint to point at.
// ---------------------------------------------------------------------------
export function webSiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": `${SITE_URL}/#website`,
    name: SITE_NAME,
    url: SITE_URL,
    description: DEFAULT_DESCRIPTION,
    publisher: { "@id": `${SITE_URL}/#organization` },
    inLanguage: "en",
  };
}

// ---------------------------------------------------------------------------
// BreadcrumbList — helps AI models understand page hierarchy
// ---------------------------------------------------------------------------
export function breadcrumbJsonLd(
  items: { name: string; url: string }[],
) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: items.map((item, i) => ({
      "@type": "ListItem",
      position: i + 1,
      name: item.name,
      item: item.url.startsWith("http") ? item.url : `${SITE_URL}${item.url}`,
    })),
  };
}

// ---------------------------------------------------------------------------
// Service — per-pillar rich schema for AI citation
// ---------------------------------------------------------------------------
export function pillarServiceJsonLd(pillar: Pillar) {
  const imageUrl = pillar.image
    ? pillar.image.startsWith("http")
      ? pillar.image
      : `${SITE_URL}${pillar.image}`
    : "";

  return {
    "@context": "https://schema.org",
    "@type": "Service",
    "@id": `${SITE_URL}/our-work/${pillar.slug}#service`,
    name: pillar.title,
    description: pillar.description,
    url: `${SITE_URL}/our-work/${pillar.slug}`,
    provider: { "@id": `${SITE_URL}/#organization` },
    areaServed: [
      { "@type": "Country", name: "Georgia" },
      { "@type": "Continent", name: "Europe" },
    ],
    serviceType: pillar.tags.join(", "),
    hasOfferCatalog: pillar.services.length > 0
      ? {
          "@type": "OfferCatalog",
          name: `${pillar.title} Services`,
          itemListElement: pillar.services.map((s) => ({
            "@type": "Offer",
            itemOffered: { "@type": "Service", name: s },
          })),
        }
      : undefined,
    ...(imageUrl ? { image: imageUrl } : {}),
  };
}

// ---------------------------------------------------------------------------
// FAQPage — for citation-worthy Q&A content
// ---------------------------------------------------------------------------
export function faqJsonLd(
  faqs: { question: string; answer: string }[],
) {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    inLanguage: "en",
    mainEntity: faqs.map((faq) => ({
      "@type": "Question",
      name: faq.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: faq.answer,
      },
    })),
  };
}

// ---------------------------------------------------------------------------
// AboutPage — explicit page type for AI understanding
// ---------------------------------------------------------------------------
export function aboutPageJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "AboutPage",
    "@id": `${SITE_URL}/about#webpage`,
    name: "About GOTT WALD Holding",
    description:
      "GOTT WALD is a unified architecture — modular components, one standard, one language of delivery. We turn complexity into clarity and decisions into measurable impact.",
    url: `${SITE_URL}/about`,
    isPartOf: { "@id": `${SITE_URL}/#website` },
    about: { "@id": `${SITE_URL}/#organization` },
    mainEntity: { "@id": `${SITE_URL}/#organization` },
    inLanguage: "en",
  };
}

// ---------------------------------------------------------------------------
// ContactPage — for AI to surface contact info
// ---------------------------------------------------------------------------
export function contactPageJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "ContactPage",
    "@id": `${SITE_URL}/contact#webpage`,
    name: "Contact GOTT WALD Holding",
    description:
      "Strategic inquiries, partnership requests, and general communication with GOTT WALD Holding LLC.",
    url: `${SITE_URL}/contact`,
    isPartOf: { "@id": `${SITE_URL}/#website` },
    // Reference the Organization node (emitted by layout.tsx) rather than
    // re-declaring contactPoint here. Prevents partially-overlapping truths.
    mainEntity: { "@id": `${SITE_URL}/#organization` },
    inLanguage: "en",
  };
}

// ---------------------------------------------------------------------------
// CollectionPage — for Our Work / Pillars listing
// ---------------------------------------------------------------------------
export function collectionPageJsonLd(
  pillars: { title: string; slug: string; description: string }[],
) {
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "@id": `${SITE_URL}/our-work#webpage`,
    name: "All Pillars — GOTT WALD Services",
    description:
      "Full registry of GOTT WALD structural pillars — modular components designed to stand alone and engineered to connect into one integrated operating system.",
    url: `${SITE_URL}/our-work`,
    isPartOf: { "@id": `${SITE_URL}/#website` },
    mainEntity: {
      "@type": "ItemList",
      itemListElement: pillars.map((p, i) => ({
        "@type": "ListItem",
        position: i + 1,
        name: p.title,
        url: `${SITE_URL}/our-work/${p.slug}`,
        description: p.description,
      })),
    },
    inLanguage: "en",
  };
}

// ---------------------------------------------------------------------------
// JobPosting helper — for careers page
// ---------------------------------------------------------------------------
export function jobPostingJsonLd(jobs: {
  title: string;
  description: string;
  pillar: string;
  datePosted?: string;
  validThrough?: string;
}[]) {
  const today = new Date();
  const defaultPosted = today.toISOString().split("T")[0];
  // Default validity: 90 days from today. Google de-indexes expired postings,
  // so a rolling window is safer than a hardcoded calendar date.
  const defaultValid = new Date(today.getTime() + 90 * 24 * 60 * 60 * 1000)
    .toISOString()
    .split("T")[0];

  return jobs.map((job) => ({
    "@context": "https://schema.org",
    "@type": "JobPosting",
    title: job.title,
    description: job.description,
    hiringOrganization: { "@id": `${SITE_URL}/#organization` },
    jobLocation: {
      "@type": "Place",
      address: {
        "@type": "PostalAddress",
        addressLocality: "Tbilisi",
        addressCountry: "GE",
      },
    },
    employmentType: "FULL_TIME",
    industry: job.pillar,
    datePosted: job.datePosted ?? defaultPosted,
    validThrough: job.validThrough ?? defaultValid,
  }));
}

// ---------------------------------------------------------------------------
// WebPage — generic schema for standalone pages (legal, directory, etc.)
// ---------------------------------------------------------------------------
export function webPageJsonLd(opts: {
  path: string;
  name: string;
  description: string;
}) {
  const url = `${SITE_URL}${opts.path}`;
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "@id": `${url}#webpage`,
    name: opts.name,
    description: opts.description,
    url,
    isPartOf: { "@id": `${SITE_URL}/#website` },
    about: { "@id": `${SITE_URL}/#organization` },
    inLanguage: "en",
  };
}

// ---------------------------------------------------------------------------
// Speakable — marks content sections as speakable for voice assistants
// ---------------------------------------------------------------------------
export function speakableJsonLd(
  pageUrl: string,
  cssSelectors: string[],
) {
  return {
    "@context": "https://schema.org",
    "@type": "WebPage",
    url: pageUrl.startsWith("http") ? pageUrl : `${SITE_URL}${pageUrl}`,
    speakable: {
      "@type": "SpeakableSpecification",
      cssSelector: cssSelectors,
    },
  };
}

// ---------------------------------------------------------------------------
// HowTo — for process-oriented content (partnerships, relocation)
// ---------------------------------------------------------------------------
export function howToJsonLd(howTo: {
  name: string;
  description: string;
  steps: { name: string; text: string }[];
}) {
  return {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: howTo.name,
    description: howTo.description,
    step: howTo.steps.map((step, i) => ({
      "@type": "HowToStep",
      position: i + 1,
      name: step.name,
      text: step.text,
    })),
  };
}

// ---------------------------------------------------------------------------
// Article / BlogPosting — for editorial content (blog posts, case studies,
// press releases). Publisher is auto-linked to the Organization node so AI
// engines can cite the company alongside the article author.
// ---------------------------------------------------------------------------
export function articleJsonLd(article: {
  type?: "Article" | "BlogPosting" | "NewsArticle";
  path: string;
  headline: string;
  description: string;
  datePublished: string;
  dateModified?: string;
  author?: { name: string; url?: string };
  image?: string;
  keywords?: string[];
}) {
  const url = `${SITE_URL}${article.path}`;
  return {
    "@context": "https://schema.org",
    "@type": article.type ?? "Article",
    "@id": `${url}#article`,
    headline: article.headline,
    description: article.description,
    url,
    mainEntityOfPage: { "@id": url },
    datePublished: article.datePublished,
    dateModified: article.dateModified ?? article.datePublished,
    author: article.author
      ? {
          "@type": "Person",
          name: article.author.name,
          ...(article.author.url ? { url: article.author.url } : {}),
        }
      : { "@id": `${SITE_URL}/#organization` },
    publisher: { "@id": `${SITE_URL}/#organization` },
    image: article.image
      ? { "@type": "ImageObject", url: article.image, width: 1200, height: 630 }
      : { "@type": "ImageObject", url: `${SITE_URL}/opengraph-image`, width: 1200, height: 630 },
    ...(article.keywords?.length ? { keywords: article.keywords.join(", ") } : {}),
    inLanguage: "en",
  };
}

// ---------------------------------------------------------------------------
// Review + AggregateRating — for testimonials and ratings. Currently no
// reviews live on-site; helpers are scaffolded so adding them is a single
// data-source change, not a schema rewrite.
// ---------------------------------------------------------------------------
export function reviewJsonLd(review: {
  itemReviewedId?: string;
  author: string;
  ratingValue: number;
  reviewBody: string;
  datePublished: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Review",
    itemReviewed: { "@id": review.itemReviewedId ?? `${SITE_URL}/#organization` },
    author: { "@type": "Person", name: review.author },
    reviewRating: {
      "@type": "Rating",
      ratingValue: review.ratingValue,
      bestRating: 5,
      worstRating: 1,
    },
    reviewBody: review.reviewBody,
    datePublished: review.datePublished,
  };
}

export function aggregateRatingJsonLd(opts: {
  ratingValue: number;
  reviewCount: number;
  itemReviewedId?: string;
}) {
  return {
    "@context": "https://schema.org",
    "@type": "AggregateRating",
    itemReviewed: { "@id": opts.itemReviewedId ?? `${SITE_URL}/#organization` },
    ratingValue: opts.ratingValue,
    bestRating: 5,
    worstRating: 1,
    reviewCount: opts.reviewCount,
  };
}

// ---------------------------------------------------------------------------
// Founder / Executive Person schema — emit on /about when bio fields are
// confirmed. Kept separate from the minimal org-level `patron` (which by
// design carries name only). When invoked, this enriched Person node binds
// the executive to the Organization via `worksFor` so AI engines can resolve
// "who runs GOTT WALD" with high confidence.
// ---------------------------------------------------------------------------
export function founderJsonLd(person: {
  name: string;
  jobTitle: string;
  description?: string;
  image?: string;
  url?: string;
  sameAs?: string[];
  alumniOf?: string[];
  awards?: string[];
}) {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": `${SITE_URL}/about#${person.name.toLowerCase().replace(/\s+/g, "-")}`,
    name: person.name,
    jobTitle: person.jobTitle,
    worksFor: { "@id": `${SITE_URL}/#organization` },
    ...(person.description ? { description: person.description } : {}),
    ...(person.image
      ? { image: { "@type": "ImageObject", url: person.image } }
      : {}),
    ...(person.url ? { url: person.url } : {}),
    ...(person.sameAs?.length ? { sameAs: person.sameAs } : {}),
    ...(person.alumniOf?.length
      ? {
          alumniOf: person.alumniOf.map((name) => ({
            "@type": "Organization",
            name,
          })),
        }
      : {}),
    ...(person.awards?.length ? { award: person.awards } : {}),
  };
}

